# **Digital forensics**

In [41]:
#Importing libraries

import pandas as pd

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [42]:
df = pd.read_csv('logs.csv')

In [43]:
df.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Action,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
0,57222,53,54587,53,0,177,94,83,2,30,1,1
1,56258,3389,56258,3389,0,4768,1600,3168,19,17,10,9
2,6881,50321,43265,50321,0,238,118,120,2,1199,1,1
3,50553,3389,50553,3389,0,3327,1438,1889,15,17,8,7
4,50002,443,45848,443,0,25358,6778,18580,31,16,13,18

In [44]:
df

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Action,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
0,57222,53,54587,53,0,177,94,83,2,30,1,1
1,56258,3389,56258,3389,0,4768,1600,3168,19,17,10,9
2,6881,50321,43265,50321,0,238,118,120,2,1199,1,1
3,50553,3389,50553,3389,0,3327,1438,1889,15,17,8,7
4,50002,443,45848,443,0,25358,6778,18580,31,16,13,18
...,...,...,...,...,...,...,...,...,...,...,...,...
65527,63691,80,13237,80,0,314,192,122,6,15,4,2
65528,50964,80,13485,80,0,4680740,67312,4613428,4675,77,985,3690
65529,54871,445,0,0,2,70,70,0,1,0,1,0
65530,54870,445,0,0,2,70,70,0,1,0,1,0
65531,54867,445,0,0,2,70,70,0,1,0,1,0

In [45]:
X = df[["Source Port", "Destination Port", "NAT Source Port", "NAT Destination Port","Bytes","Bytes Sent","Bytes Received","Packets","Elapsed Time (sec)","pkts_sent","pkts_received"]]
Y = df["Action"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0, stratify=Y)

In [46]:
#inicializing XGBoost
model = XGBClassifier(max_depth=5, min_child_weight=1, n_estimators=200, n_jobs=-1, learning_rate=0.15)

# Adding silent=True to avoid printing out updates with each cycle
model.fit(X_train, Y_train)

#making prediction
y_pred = model.predict(X_test)

In [47]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[7526    2    0    0]
 [   1 2989    7    1]
 [   0    0 2570    0]
 [   0    8    0    3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7528
           1       1.00      1.00      1.00      2998
           2       1.00      1.00      1.00      2570
           3       0.75      0.27      0.40        11

    accuracy                           1.00     13107
   macro avg       0.94      0.82      0.85     13107
weighted avg       1.00      1.00      1.00     13107

In [48]:
accuracy = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00

In [49]:
print("Train accuracy:", model.score(X_train, Y_train))
print("Test accuracy:", model.score(X_test, Y_test))

Train accuracy: 0.9990271816881259
Test accuracy: 0.9985503929198138

Train and test are: almost identical and both extremely high
- This is good generalization
- Model is not overfitting